import { Metadata } from 'next';
import { siteConfig } from '@/lib/site';

export const metadata: Metadata = {
  title: siteConfig.name,
  description: siteConfig.description,
  keywords: [
    'website ontwikkeling',
    'webapplicatie ontwikkeling',
    'webdesign',
    'cloudbeheer',
    'cybersecurity',
    'website laten maken',
    'webapplicatie laten maken',
    'website ontwikkelaar',
    'webdeveloper',
    'cloud oplossingen',
    'cloud beheer',
    'cybersecurity diensten',
    'website onderhoud',
    'webdesign bureau',
    'digitale oplossingen',
    'moderne websites',
    'responsive webdesign',
    'SEO optimalisatie',
    'cloud infrastructuur',
    'security audits',
    'penetration testing',
    'GDPR compliance',
    'website hosting',
    'webapplicatie ontwikkeling Nederland',
    'cloudbeheer Nederland',
    'cybersecurity Nederland',
    'TynkTech',
    'Tynk Tech',
    'website op maat',
    'webapplicatie op maat',
    'cloud services',
    'security consulting',
    'website beveiliging',
    'webapplicatie beveiliging',
    'cloud security',
    'IT beveiliging',
    'website optimalisatie',
    'web performance',
    'API ontwikkeling',
    'full-stack ontwikkeling',
    'frontend ontwikkeling',
    'backend ontwikkeling',
    'UI/UX design',
    'website redesign',
    'e-commerce ontwikkeling',
    'woocommerce ontwikkeling',
    'shopify ontwikkeling',
    'magento ontwikkeling',
    'wordpress ontwikkeling',
    'react ontwikkeling',
    'next.js ontwikkeling',
    'node.js ontwikkeling',
    'typescript ontwikkeling',
    'javascript ontwikkeling',
    'php ontwikkeling',
    'python ontwikkeling',
    'database ontwikkeling',
    'mobile-first design',
    'progressive web app',
    'single page application',
    'website migratie',
    'cloud migratie',
    'AWS beheer',
    'Azure beheer',
    'Google Cloud beheer',
    'server beheer',
    'server monitoring',
    'backup oplossingen',
    'disaster recovery',
    'website uptime',
    'SSL certificaten',
    'HTTPS implementatie',
    'website snelheid',
    'page speed optimalisatie',
    'core web vitals',
    'website analytics',
    'google analytics',
    'conversie optimalisatie',
    'A/B testing',
    'website testing',
    'accessibility',
    'WCAG compliance',
    'website toegankelijkheid',
  ],
  authors: [
    {
      name: 'Tynk Technologys V.O.F',
      url: 'https://tynktech.ai',
    },
  ],
  creator: 'Tynk Technologys V.O.F',
  openGraph: {
    type: 'website',
    locale: 'nl_NL',
    url: siteConfig.url,
    title: 'TynkTech – Moderne Websites, Webapplicaties, Cloud & Cybersecurity',
    description: 'TynkTech is een innovatief technologiebedrijf gespecialiseerd in moderne websites, webapplicaties, cloud-oplossingen en cybersecurity. Professioneel webdesign, cloudbeheer en geavanceerde beveiliging voor jouw bedrijf.',
    siteName: 'TynkTech',
    images: [
      {
        url: '/banner.png',
        width: 1200,
        height: 630,
        alt: siteConfig.name,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.name,
    description: siteConfig.description,
    creator: '@tynktech',
    images: ['/banner.png'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};
